# vim:ts=4:sw=4:et

name: ai-tools

services:
    agents:
        build:
            context: .
            dockerfile: Dockerfile.agents
            args:
                - MY_USERNAME=${MY_USERNAME}
                - MY_UID=${MY_UID}
                - MY_GID=${MY_GID}
        image: openavr/${COMPOSE_PROJECT_NAME}-agents-${MY_USERNAME}:1.0.0
        network_mode: "bridge"
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - $HOME/.gitconfig:$HOME/.gitconfig:ro
            - opencode-share:$HOME/.local/share/opencode
            - opencode-state:$HOME/.local/state/opencode
            - agents-workdir:$HOME/workdir
        user: ${MY_UID}:${MY_GID}

    ollama:
        build:
            context: .
            dockerfile: Dockerfile.ollama
        image: openavr/${COMPOSE_PROJECT_NAME}-ollama:1.0.0
        ports:
            - "11434:11434"
        volumes:
            - ollama-data:/root/.ollama
        environment:
            - OLLAMA_HOST=0.0.0.0:11434
            - OLLAMA_MODELS=/root/.ollama/models
            - OLLAMA_NO_CLOUD=1
            - OLLAMA_DEBUG=1
            - OLLAMA_KEEP_ALIVE=-1
            - NVIDIA_VISIBLE_DEVICES=all
        runtime: nvidia

volumes:
    opencode-share:
    opencode-state:
    agents-workdir:
    ollama-data:
