FROM debian:trixie

# These values should be coming from the generated `.env` file.
ARG MY_USERNAME
ARG MY_UID
ARG MY_GID

ENV USERNAME=${MY_USERNAME:-dumbass}
ENV UID=${MY_UID:-1000}
ENV GID=${MY_GID:-1000}

USER root

RUN apt-get update \
    && apt-get install -y \
        apt-transport-https \
        bash \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        fd-find \
        file \
        git \
        gnupg \
        iproute2 \
        iputils-ping \
        jq \
        kitty-terminfo \
        less \
        lsb-release \
        lsof \
        procps \
        python3-venv \
        ripgrep \
        sudo \
        tmux \
        tree \
        unzip \
        vim \
        wget \
        zip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L -v https://github.com/neovim/neovim/releases/download/v0.12.3/nvim-linux-x86_64.tar.gz \
        -o /tmp/nvim.tar.gz \
    && ls -al /tmp \
    && tar -C /usr/local -xf /tmp/nvim.tar.gz --strip-components=1

# Do not run as root, use sudo without password; might be useless
RUN groupadd -g ${GID} ${USERNAME} \
    && useradd -u ${UID} -g ${GID} -m -s /bin/bash ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME}

# Set the default shell to bash instead of dash
RUN echo "dash dash/sh boolean false" | debconf-set-selections \
    && dpkg-reconfigure dash

RUN \
    mkdir -p /home/${USERNAME}/.local && \
    mkdir -p /home/${USERNAME}/workspace && \
    chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}

USER ${USERNAME}
WORKDIR /home/${USERNAME}

RUN curl -fsSL https://opencode.ai/install | /bin/bash
RUN curl -fsSL https://cursor.com/install | /bin/bash
RUN curl -fsSL https://claude.ai/install.sh | /bin/bash

# Default working directory (overridden at runtime by --workdir)
WORKDIR /home/${USERNAME}/workspace
CMD ["/bin/bash", "-l"]
